name: Build & Ship

on:
  push:
    branches:
      - main # Trigger the  workflow on push event to the main branch

env:
  APP_NAME: mordecaix

jobs:
  # Step 1: 读取属性文件
  read-properties:
    runs-on: ubuntu-latest
    outputs:
      api_key: ${{ steps.read.outputs.the_key_of_a_property }}
      another_key: ${{ steps.read.outputs.the_key_of_another_property }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Read Properties File
        id: read
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './gradle.properties'
          properties: 'version.name.desktop version.name.app version.name.web'

  web-build:
    needs: read-properties
    runs-on: ubuntu-latest
    timeout-minutes: 45 # Set the timeout of 45 minutes for this job
    steps:
      - uses: actions/checkout@v4  # Use checkout to support cloning local projects to runner environment
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # Use Zulu provide jdk
          java-version: 17
          cache: 'gradle'
          cache-dependency-path: | # regex to match all sub-projects
            **/*.gradle*
            **/gradle-wrapper.properties

      - name: Build web js app
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          max_attempts: 2
          command: ./gradlew :composeApp:jsBrowserDevelopmentExecutableDistribution

      - name: Push WebAssembly build output to another repository
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }}
        with:
          source-directory: composeApp/build/dist/js/developmentExecutable
          destination-github-username: 'crowforkotlin'
          destination-repository-name: 'mordecaix-pages-js'
          user-email: crowforkotlin@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          create-target-branch-if-needed: true
          target-branch: js


  wasm-build:
    needs: read-properties
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'
          cache-dependency-path: | # regex to match all sub-projects
            **/*.gradle*
            **/gradle-wrapper.properties

      - name: Build wasm app
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          max_attempts: 2
          command: ./gradlew :composeApp:wasmBrowserDevelopmentExecutableDistribution
      - name: Push WebAssembly build output to another repository
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }}
        with:
          source-directory: composeApp/build/dist/wasmJs/developmentExecutable
          destination-github-username: 'crowforkotlin'
          destination-repository-name: 'mordecaix-pages-wasmjs'
          user-email: crowforkotlin@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          create-target-branch-if-needed: true
          target-branch: wasmJs


  desktop-build:
    needs: read-properties
    runs-on: windows-latest
    timeout-minutes: 45 # 设置超时时间为 45 分钟
    steps:
      - uses: actions/checkout@v4
      - name: print
        run: |
          echo "Windows Release App - ${{ env.APP_NAME }}${{ needs.read-properties.version.name.desktop }}.exe"
      - name: Download and Extract JBR
        run: |
          mkdir -p C:\jbr
          curl -L -o C:\jbr.tar.gz https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-17.0.11-windows-x64-b1312.2.tar.gz
      - name: Configure JAVA_HOME
        uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: C:\jbr.tar.gz
          java-version: '17.0.11'
          cache: 'gradle'
          cache-dependency-path: | # regex to match all sub-projects
            **/*.gradle*
            **/gradle-wrapper.properties
      - name: Build Windows Debug App
        run: |
          .\gradlew packageUberJarForCurrentOS
          .\gradlew createDistributable
          .\gradlew packageExe
      - name: Archive Windows Debug Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows Debug App - ${{ env.APP_NAME }}${{ needs.read-properties.version.name.desktop }}.exe
          if-no-files-found: ignore
          path: composeApp/build/compose/binaries/main/app
      - name: Build Windows Release App
        run: |
          .\gradlew createReleaseDistributable
          .\gradlew packageReleaseExe
      - name: Archive Windows Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows Release App
          if-no-files-found: ignore
          path: composeApp/build/compose/binaries/main-release/app
      - name: Archive Windows Release App Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows Release App - ${{ env.APP_NAME }}${{ needs.read-properties.version.name.desktop }}.exe
          if-no-files-found: ignore
          path: composeApp/build/compose/binaries/main-release/exe/*
      - name: Print Test
        run: |
          ls composeApp/build/compose/binaries
          ls composeApp/build/compose/binaries/main
          ls composeApp/build/compose/binaries/main-release

  android-build:
    needs: read-properties
    runs-on: ubuntu-latest
    timeout-minutes: 45 # 设置超时时间为 45 分钟
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # Use Zulu provide jdk
          java-version: 17
          cache: 'gradle'
          cache-dependency-path: | # regex to match all sub-projects
            **/*.gradle*
            **/gradle-wrapper.properties
      - name: Build Android Debug App
        run: |
          ./gradlew assembleDebug
      - name: Archive Debug Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Android Debug Apk
          if-no-files-found: ignore
          path: composeApp/build/outputs/apk/debug
      - name: Build Android Release App
        run: |
          ./gradlew assembleRelease
      - name: Archive Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Android Release Apk
          if-no-files-found: ignore
          path: composeApp/build/outputs/apk/release