name: Build & Ship

on:
  push:
    branches:
      - main # Trigger the  workflow on push event to the main branch

jobs:
  web-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45 # Set the timeout of 45 minutes for this job

    steps:
      - uses: actions/checkout@v4  # Use checkout to support cloning local projects to runner environment
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # Use Zulu provide jdk
          java-version: 17

      - name: Build web js app
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          max_attempts: 2
          command: ./gradlew :composeApp:jsBrowserDevelopmentExecutableDistribution

      - name: Push WebAssembly build output to another repository
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }}
        with:
          source-directory: composeApp/build/dist/js/developmentExecutable
          destination-github-username: 'crowforkotlin'
          destination-repository-name: 'mordecaix-pages-js'
          user-email: crowforkotlin@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          create-target-branch-if-needed: true
          target-branch: js

  wasm-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build wasm app
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          max_attempts: 2
          command: ./gradlew :composeApp:wasmBrowserDevelopmentExecutableDistribution

      - name: Push WebAssembly build output to another repository
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }}
        with:
          source-directory: composeApp/build/dist/wasmJs/developmentExecutable
          destination-github-username: 'crowforkotlin'
          destination-repository-name: 'mordecaix-pages-wasmjs'
          user-email: crowforkotlin@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          create-target-branch-if-needed: true
          target-branch: wasmJs
