name: Build & Ship

on:
  push:
    branches:
      - dev  # 仅当推送到 main 分支时触发
  pull_request:
    types: [ closed ]  # 检测 PR 合并事件
    branches:
      - main  # 仅当 PR 合并到 main 分支时触发

env:
  APP_NAME: mordecaix

jobs:
  # Step 1: 读取属性文件
  read-properties:
    runs-on: ubuntu-latest
    outputs: # 定义 job 的输出
      version_name_desktop: ${{ steps.properties.outputs.version-name-desktop }}
      version_name_app: ${{ steps.properties.outputs.version-name-app }}
      version_name_web: ${{ steps.properties.outputs.version-name-web }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Read Properties File
        id: 'properties'
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './gradle.properties'
          properties: 'version.name.desktop version.name.app version.name.web'


  macos-desktop-build:
    needs: read-properties
    runs-on: macos-latest
    timeout-minutes: 45 # 设置超时时间为 45 分钟
    steps:
      - uses: actions/checkout@v4
      - name: Download and Extract JBR
        run: |
          mkdir -p /Users/runner/jbr
          curl -L -o /Users/runner/jbr.tar.gz https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-17.0.11-osx-aarch64-b1312.2.tar.gz
      - name: Configure JAVA_HOME
        uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: /Users/runner/jbr.tar.gz
          java-version: '17.0.11'
          cache: 'gradle'
          cache-dependency-path: | # regex to match all sub-projects
            **/*.gradle*
            **/gradle-wrapper.properties
      - name: Build Macos Debug App
        run: |
          ./gradlew packageUberJarForCurrentOS
          ./gradlew createDistributable
          ./gradlew packagePkg
      - name: Archive Macos Debug App Installer Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Macos Debug App Installer - ${{ env.APP_NAME }}-${{ needs.read-properties.outputs.version_name_desktop }}
          if-no-files-found: ignore
          path: composeApp/build/compose/binaries/main/app
      - name: Archive Macos Debug Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Macos Debug App - ${{ env.APP_NAME }}-${{ needs.read-properties.outputs.version_name_desktop }}
          if-no-files-found: ignore
          path: composeApp/build/compose/binaries/main/
      - name: Build Macos Release App
        run: |
          ./gradlew createReleaseDistributable
          ./gradlew packageReleasePkg
      - name: Archive Macos Release App Installer Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Macos Release App Installer - ${{ env.APP_NAME }}-${{ needs.read-properties.outputs.version_name_desktop }}
          if-no-files-found: ignore
          path: composeApp/build/compose/binaries/main-release/app
      - name: Archive Macos Release App Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Macos Release App - ${{ env.APP_NAME }}-${{ needs.read-properties.outputs.version_name_desktop }}
          if-no-files-found: ignore
          path: composeApp/build/compose/binaries/main-release/deb
