name: Build & Ship
on:
  push:
    branches:
      - main
jobs:
  web-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build web app
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          max_attempts: 2
          command: ./gradlew :composeApp:jsBrowserDevelopmentExecutableDistribution
          
      - name: logact
        run: ls composeApp/build/
        
      - name: Push WebAssembly build output to another repository
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }}
        with:
          source-directory: composeApp/build/dist/js
          destination-github-username: 'crowforkotlin'
          destination-repository-name: 'testyml1'
          user-email: crowforkotlin@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main


  wasm-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build wasm app
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          max_attempts: 2
          command: ./gradlew :composeApp:wasmBrowserDevelopmentExecutableDistribution
